### ISSUE TITLE
Excuse me, after each round, how do you know who has won?

### ISSUE THREAD

**Issue by qingfeng** [SirRender00/texasholdem#124]
Excuse me, after each round, how do you know who has won?
No corresponding function or variable found

How to know what type of hand the winning player has, such as a straight, two pair

thanks

**Comment by SirRender00** [comment]
Yeah so in the [hand history attribute](https://texasholdem.readthedocs.io/en/stable/texasholdem.game.html#texasholdem.game.game.TexasHoldEm.hand_history) which is of type [History](https://texasholdem.readthedocs.io/en/stable/texasholdem.game.html#texasholdem.game.history.History), we can get that information.

e.g.

```
game.hand_history[HandPhase.SETTLE].pot_winners == {0: (1192, -1, [4])}
```

Which is keyed by pot id and the value can be read: 1192 chips, rank of the winning hand (-1 because there was no contest everyone folded), winning player ids (in this case one winner player 4).

**Comment by SirRender00** [comment]
For your second question, I think that might be answered in the [quickstart section of the docs](https://texasholdem.readthedocs.io/en/stable/getting_started.html#poker-evaluator)

For verboseness, the [evaluator module](https://texasholdem.readthedocs.io/en/stable/texasholdem.evaluator.html) has the [evaluate function](https://texasholdem.readthedocs.io/en/stable/texasholdem.evaluator.html#texasholdem.evaluator.evaluator.evaluate) that returns the hand rank 1 - 7462, 1 being the best. 

With that hand rank, there is the [rank_to_string function](https://texasholdem.readthedocs.io/en/stable/texasholdem.evaluator.html#texasholdem.evaluator.evaluator.rank_to_string) which translates it to a human-readable format.

**Comment by qingfeng** [comment]
Thank you so much 👍

**Comment by SirRender00** [comment]
Yeah for sure, feel free to add suggestions if you feel like this could be improved.
