### ISSUE TITLE
A question about take_action

### ISSUE THREAD

**Issue by qingfeng** [SirRender00/texasholdem#125]
I try to do as follows

fake code:
take_action(RAISE, 20)

The next player, let's say it should be CALL 20
take_action(CHECK, 0)

But I call CHECK, CALL, it seems to be successful?

**Comment by SirRender00** [comment]
In your code, after the end of the game can you do `game.export_history("./texas.pgn")` and paste / screenshot it here? It would help with debugging.

Another thing to note is that `RAISE` is read as `RAISE _to_ amount` so that the argument you pass it will be the total. (For now, working on changing this to mean `RAISE` an amount above the current bet.)

**Comment by SirRender00** [comment]
Closing this as no response given. Feel free to reopen or recreate
